### ISSUE TITLE
Link to "latest GPL version" in about page appears to be broken

### ISSUE THREAD

**Issue by RoyTinker** [richardjs/Maelstrom#1]
This link in the About page appears to be broken: http://www.devolution.com/~slouken/Maelstrom/

**Comment by richardjs** [comment]
Old issue! It feels embarrassing to even say "sorry for the delay".

That link is in the part of the README that's from the original Maelstrom 3.0 README. Even if it's broken, I'd like to preserve it for now, for archival purposes. I updated the format, though, to make it more obvious I'm quoting the original README at that point.

Thanks!
