### ISSUE TITLE
Missing header files from Maelstrom-netd.c

### ISSUE THREAD

**Issue by jserio1869** [richardjs/Maelstrom#3]
Have just done a clone and build of the Maelstrom code using Mac OS 11.1 Big Sur. Successful! One slight change that I needed to perform - #include <stdlib.h> and #include <arpa/inet.h> being added to Maelstrom-netd.c. I decided I didn't want to create a whole branch for just this minor change. Great work on this!

**Comment by richardjs** [comment]
I have done so. Thanks!
